Vagrant.configure("2") do |config|
  config.vm.provider :aws do |aws, _|
    aws.region_config "us-east-1", :ami => "ami-70504266"
    aws.region_config "us-east-2", :ami => "ami-0d725268"
    aws.region_config "us-west-1", :ami => "ami-8b0128eb"
    aws.region_config "us-west-2", :ami => "ami-dda7bea4"
    aws.region_config "sa-east-1", :ami => "ami-9ad8acf6"
    aws.region_config "eu-west-1", :ami => "ami-5302ec2a"
    aws.region_config "eu-west-2", :ami => "ami-f2425396"
    aws.region_config "eu-central-1", :ami => "ami-7588251a"
    aws.region_config "ap-northeast-1", :ami => "ami-0a50b66c"
    aws.region_config "ap-northeast-2", :ami => "ami-f575ab9b"
    aws.region_config "ap-southeast-1", :ami => "ami-6d75e50e"
    aws.region_config "ap-southeast-2", :ami => "ami-bda2bede"
    aws.region_config "ap-south-1", :ami => "ami-8a760ee5"
    aws.region_config "sa-east-1", :ami => "ami-9ad8acf6"
  end
end
