Vagrant.configure("2") do |config|
  config.vm.provider :aws do |aws, _|
    aws.region_config "ap-northeast-1", :ami => "ami-3e25f341"
    aws.region_config "ap-northeast-2", :ami => "ami-54bd083a"
    aws.region_config "ap-south-1", :ami => "ami-941520fb"
    aws.region_config "ap-southeast-1", :ami => "ami-57f0f22b"
    aws.region_config "ap-southeast-2", :ami => "ami-2e25fc4c"
    aws.region_config "ca-central-1", :ami => "ami-a2f97bc6"
    aws.region_config "eu-central-1", :ami => "ami-2b97a8c0"
    aws.region_config "eu-west-1", :ami => "ami-cb202e21"
    aws.region_config "eu-west-2", :ami => "ami-ccb75eab"
    aws.region_config "eu-west-3", :ami => "ami-fcf54581"
    aws.region_config "sa-east-1", :ami => "ami-7147621d"
    aws.region_config "us-east-1", :ami => "ami-e83e6c97"
    aws.region_config "us-east-2", :ami => "ami-3bd2eb5e"
    aws.region_config "us-west-1", :ami => "ami-f0df3993"
    aws.region_config "us-west-2", :ami => "ami-37df964f"
  end
end
