Vagrant.configure("2") do |config|
  config.vm.provider :aws do |aws, _|
    aws.region_config "af-south-1", :ami => "ami-0183ba5b381eb0baa"
    aws.region_config "eu-north-1", :ami => "ami-0821c256650690884"
    aws.region_config "ap-south-1", :ami => "ami-009471f6e29b012ef"
    aws.region_config "eu-west-3", :ami => "ami-0bfaf7527f637d64b"
    aws.region_config "eu-west-2", :ami => "ami-023d320201b8d06c5"
    aws.region_config "eu-south-1", :ami => "ami-08828d09ef0598bc8"
    aws.region_config "eu-west-1", :ami => "ami-02b1b6bc3cface0ac"
    aws.region_config "ap-northeast-2", :ami => "ami-03f41a1a8d06363a5"
    aws.region_config "me-south-1", :ami => "ami-0e1e55e0288018f35"
    aws.region_config "ap-northeast-1", :ami => "ami-0a352b6e005340d93"
    aws.region_config "sa-east-1", :ami => "ami-0b9c77455fbf5f3f0"
    aws.region_config "ca-central-1", :ami => "ami-0dbf9b82233b2b970"
    aws.region_config "ap-east-1", :ami => "ami-0f4732ac090ec2a7d"
    aws.region_config "ap-southeast-1", :ami => "ami-045943797617e690c"
    aws.region_config "ap-southeast-2", :ami => "ami-0cbc4c8a75ded8b2d"
    aws.region_config "eu-central-1", :ami => "ami-0d94faf9636228402"
    aws.region_config "us-east-1", :ami => "ami-00be86d9bba30a7b3"
    aws.region_config "us-east-2", :ami => "ami-075db5a7ecd8b1456"
    aws.region_config "us-west-1", :ami => "ami-0e54f016b55b7f6ce"
    aws.region_config "us-west-1", :ami => "ami-0c273f14bc9df57d1"
  end
end
