Vagrant.configure("2") do |config|
  config.vm.provider :aws do |aws, override|
    aws.region = "eu-west-1"
    aws.ami = "ami-c847b2bf"
    aws.instance_type = "m3.medium"
    aws.security_groups = ["FreeBSD Default"]

    override.ssh.username = "ec2-user"
  end
end
